name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        cd green-sisya/server
        npm install

    - name: Build the project
      run: |
        cd green-sisya/server
        npm run build

    - name: Set up SSH for server connection
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 212.193.30.159 >> ~/.ssh/known_hosts

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: 212.193.30.159
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/green-sisya
          git pull
          docker-compose down
          docker-compose up -d --build
